volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    container_name: kittygram-db
    image: postgres:13.10
    env_file: .env
    restart: always
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    container_name: kittygram-backend
    image: 0legrogovenko/kittygram_backend
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media_volume:/media
  frontend:
    container_name: kittygram-frontend
    image: 0legrogovenko/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /backend_static/
    volumes:
      - static_volume:/backend_static
  gateway:
    container_name: kittygram-gateway
    image: 0legrogovenko/kittygram_gateway
    env_file: .env
    restart: always
    depends_on:
      - backend
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media
    ports:
      - 9000:80